apiVersion: v1
name: harbor-scanner-trivy
version: 0.14.0
appVersion: "0.17.0"
description: Harbor scanner adapter for Trivy
keywords:
  - scanner
  - harbor
  - vulnerability
sources:
- https://github.com/aquasecurity/harbor-scanner-trivy
